In [1]:
#----------------------------------------------------------#
# CVS to CSVDataset MegaSena
#----------------------------------------------------------#
import numpy as np
import pandas as pd

path = "./mega_sena_sorteio.csv"
index = "Concurso"

df = pd.read_csv(path, index_col=index)
df.sort_values(by=["Concurso"],ascending=True,inplace=True)

In [2]:
#----------------------------------------------------------#
# Creating the array to convert the data
#----------------------------------------------------------#
concurso_1 = [0,0,0,0,0,0]
array_line = [0,0,0,0,0,0,0]
mega_array = [0,0,0,0,0,0,0]

for dezenas in df.iterrows():

    concurso_0 = [dezenas[1][1]/60, dezenas[1][2]/60, dezenas[1][3]/60, 
                  dezenas[1][4]/60, dezenas[1][5]/60, dezenas[1][6]/60]
    concurso = concurso_1
    concurso = np.append(concurso, concurso_0)

    for index in [0,1,2,3,4,5]:
        array_row = [concurso[index + 0], concurso[index + 1], concurso[index + 2], concurso[index + 3], 
                     concurso[index + 4], concurso[index + 5], concurso[index + 6]]
        if array_row[0] != 0:
            mega_array = np.vstack([mega_array, array_row])

    concurso_1 = concurso_0
#----------------------------------------------------------#
print(mega_array)
print(len(mega_array))


[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.68333333 0.08333333 0.06666667 ... 0.5        0.55       0.15      ]
 [0.08333333 0.06666667 0.86666667 ... 0.55       0.15       0.65      ]
 ...
 [0.5        0.41666667 0.36666667 ... 0.2        0.23333333 0.56666667]
 [0.41666667 0.36666667 0.53333333 ... 0.23333333 0.56666667 0.55      ]
 [0.36666667 0.53333333 0.2        ... 0.56666667 0.55       0.16666667]]
14413


In [3]:
#----------------------------------------------------------#
#  Export the data to a CSV file
#----------------------------------------------------------#
mega_csv = np.delete(mega_array, 0, 0)
df_ms = pd.DataFrame(mega_csv)
filecsv = "./MegaSena_Torch_MLP.csv"
df_ms.to_csv(filecsv, index=False,header=False)
#----------------------------------------------------------#
print(mega_csv)
print(len(mega_csv))

[[0.68333333 0.08333333 0.06666667 ... 0.5        0.55       0.15      ]
 [0.08333333 0.06666667 0.86666667 ... 0.55       0.15       0.65      ]
 [0.06666667 0.86666667 0.5        ... 0.15       0.65       0.61666667]
 ...
 [0.5        0.41666667 0.36666667 ... 0.2        0.23333333 0.56666667]
 [0.41666667 0.36666667 0.53333333 ... 0.23333333 0.56666667 0.55      ]
 [0.36666667 0.53333333 0.2        ... 0.56666667 0.55       0.16666667]]
14412


In [ ]:
#----------------------------------------------------------#
#  That is all Folks!
#----------------------------------------------------------#